- name: Install required packages.
  apt:
    name:
      - apt-transport-https
      - ca-certificates
      - curl
      - gnupg-agent
      - software-properties-common
      # python requirements
      - python-dev
      - libffi-dev
      - libssl-dev
      - gcc
      - libc-dev
      - make
      - gnupg2
      - pass

- name: Add Docker’s official GPG key.
  apt_key:
    url: https://download.docker.com/linux/ubuntu/gpg
    state: present

- name: Add dockers apt repo.
  template:
    src: "templates/etc/apt/sources.list.d/docker.list.j2"
    dest: "/etc/apt/sources.list.d/docker.list"
  register: _apt_repo_result

- name: Update apt-cache when sources.list change. # noqa 503
  apt:
    update_cache: yes
  when: _apt_repo_result.changed

- name: Install docker os packages.
  apt:
    name:
      - docker-ce
      - docker-ce-cli

- name: Install docker-compose.
  pip:
    name:
      - docker-compose

- name: Deploy docker service file
  template:
    src: "templates/etc/systemd/system/docker.service.j2"
    dest: "/etc/systemd/system/docker.service"
  notify:
    - Docker restart

- name: Remove DOCKER_CONFIG env var from environment.
  lineinfile:
    path: /etc/environment
    regexp: '^DOCKER_CONFIG='
    state: absent

- name: Create DOCKER_CONFIG profile script
  copy:
    dest: /etc/profile.d/docker.sh
    content: |
      # ANSIBLE MANAGED
      export DOCKER_CONFIG="${HOME}/.docker/"
    mode: +x

- name: Enable docker service and ensure it is started.
  service:
    name: docker
    state: started
    enabled: yes